# .github/workflows/build.yaml

# This workflow will do a clean install of node dependencies and run tests on
# the built image files.
# code and run tests across different versions of node on ubuntu, macos and
# windows.
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [main, develop, test]
    # Or use branches-ignore.
  pull_request:
    branches: [main, develop]
    # Or use branches-ignore.

jobs:
  build:
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        runs-on: [ubuntu-latest]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.runs-on }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run ci
